modLoader = "lowcodefml"
loaderVersion = "[1,]"
license = "LicenseRef-Custom"
showAsResourcePack = false
issueTrackerURL = ""

[[mods]]
modId = "recondite"
version = "0.1.0"
displayName = "Recondite"
displayURL = ""
description = ''' '''
logoFile = "pack.png"
logoBlur = false
updateJSONURL = ""
credits = "BananaKingXO"
authors = "Alligator"

[[dependencies.recondite]]
modId = "forge"
mandatory = false
versionRange = "[51,]"
ordering = "NONE"
side = "BOTH"
[[dependencies.recondite]]
modId = "minecraft"
mandatory = true
versionRange = "[26.2,26.3]"
ordering = "NONE"
side = "BOTH"
